# Generated by Django 2.2.5 on 2019-10-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Carrera', models.CharField(max_length=10)),
                ('Nombre_Carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Documento', models.CharField(max_length=30)),
                ('Numero_Identificacion', models.CharField(max_length=40)),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('carreras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Carreras')),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Libro', models.CharField(max_length=10)),
                ('Titulo', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('Editorial', models.CharField(max_length=100)),
                ('categorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categorias')),
                ('estudiantes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Prestamo', models.DateField()),
                ('Estado_Prestamo', models.CharField(max_length=50)),
                ('estudiantes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Estudiantes')),
                ('libros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Libros')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Tipo_Documento', models.CharField(max_length=30)),
                ('Numero_Identificacion', models.CharField(max_length=40)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Usuario', models.CharField(max_length=30)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Renovacion', models.DateField()),
                ('prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Prestamos')),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('Identificador_Referencia', models.AutoField(primary_key=True, serialize=False)),
                ('libros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Libros')),
            ],
        ),
        migrations.AddField(
            model_name='prestamos',
            name='referencia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Referencias'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Devolucion', models.DateField()),
                ('prestamo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Prestamos')),
            ],
        ),
    ]
