# Generated by Django 2.2.5 on 2019-10-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Tipo_Documento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('TP', 'Tarjeta de Pasaporte'), ('RC', 'Registro Civil'), ('CE', 'Cedula de Extranjeria')], default='CC', max_length=2),
        ),
    ]
