# Generated by Django 2.2.5 on 2019-09-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='Fecha_Devolucion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='Fecha_Prestamo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='renovacion',
            name='Fecha_Renovacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Fecha_Nacimiento',
            field=models.DateField(),
        ),
    ]
