# Generated by Django 2.2.5 on 2019-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191014_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='Tipo_Documento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('TP', 'Tarjeta de Pasaporte'), ('RC', 'Registro Civil'), ('CE', 'Cedula de Extranjeria')], default='CC', max_length=2),
        ),
    ]
